# Generated by Django 6.0.6 on 2026-07-18 19:00

import django.db.models.deletion
import lifetracker.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order among siblings (lower numbers appear first).')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasktracker.task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Leave blank to auto-populate from the uploaded file name.', max_length=255)),
                ('date', models.DateField(blank=True, help_text='Optional date for this attachment. Leave blank to auto-extract from the filename, or if no date can be found in the filename.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(storage=lifetracker.core.models.DatabaseStorage(), upload_to='')),
                ('file_type', models.ForeignKey(blank=True, help_text='Type of the uploaded file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to='core.filetype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasktracker.task')),
            ],
            options={
                'verbose_name': 'Task Attachment',
                'verbose_name_plural': 'Task Attachments',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Optional model that tasks of this type may link to. Leave blank if tasks of this type never link to another object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasktracker.tasktype'),
        ),
    ]
