# Generated by Django 6.0.6 on 2026-07-03 05:41

import django.db.models.deletion
import django.utils.timezone
import lifetracker.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='The year in which the FY ends, e.g. 2024 for FY2024 (1 July 2023 – 30 June 2024).', unique=True)),
                ('status', models.CharField(choices=[('pending_submission', 'Pending submission to tax agent'), ('submitted', 'Submitted to tax agent'), ('more_info_requested', 'Tax agent requests more info'), ('finalised', 'Finalised')], default='pending_submission', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('lodgement_date_override', models.DateField(blank=True, help_text='Optional override of the default lodgement date (31 October of the ending year), e.g. as advised by a tax agent.', null=True)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYearStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending_submission', 'Pending submission to tax agent'), ('submitted', 'Submitted to tax agent'), ('more_info_requested', 'Tax agent requests more info'), ('finalised', 'Finalised')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('pending_submission', 'Pending submission to tax agent'), ('submitted', 'Submitted to tax agent'), ('more_info_requested', 'Tax agent requests more info'), ('finalised', 'Finalised')], max_length=30)),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='taxtracker.financialyear')),
            ],
            options={
                'verbose_name': 'Financial Year Status Transition',
                'verbose_name_plural': 'Financial Year Status Transitions',
                'ordering': ['-transitioned_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order among siblings (lower numbers appear first).')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxtracker.item')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taxtracker.financialyear')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Leave blank to auto-populate from the uploaded file name.', max_length=255)),
                ('date', models.DateField(blank=True, help_text='Optional date for this attachment. Leave blank to auto-extract from the filename, or if no date can be found in the filename.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(storage=lifetracker.core.models.DatabaseStorage(), upload_to='')),
                ('file_type', models.ForeignKey(blank=True, help_text='Type of the uploaded file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.filetype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='taxtracker.item')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['title'],
            },
        ),
    ]
