# Generated by Django 6.0.6 on 2026-07-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("taxtracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="taxtracker.item",
            ),
        ),
        migrations.CreateModel(
            name="ReceivedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_documents",
                        to="taxtracker.financialyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Received Document",
                "verbose_name_plural": "Received Documents",
                "ordering": ["-date", "title"],
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="received_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="taxtracker.receiveddocument",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("item__isnull", False), ("received_document__isnull", True)
                    ),
                    models.Q(
                        ("item__isnull", True), ("received_document__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="attachment_exactly_one_parent",
            ),
        ),
    ]
