# Generated by Django 6.0.3 on 2026-03-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='The year in which the FY ends, e.g. 2024 for FY2024 (1 July 2023 – 30 June 2024).', unique=True)),
                ('notes', models.TextField(blank=True)),
                ('lodgement_date_override', models.DateField(blank=True, help_text='Optional override of the default lodgement date (31 October of the ending year), e.g. as advised by a tax agent.', null=True)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order among siblings (lower numbers appear first).')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracker.item')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.financialyear')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, help_text='e.g. PDF, Word, CSV, Image', max_length=50)),
                ('file', models.FileField(upload_to='attachments/%Y/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracker.item')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['title'],
            },
        ),
    ]
