# Generated by Django 6.0.3 on 2026-04-14 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Short human-readable name, e.g. PDF', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Full human-readable name, e.g. PDF Document', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'File Type',
                'verbose_name_plural': 'File Types',
                'ordering': ['short_name'],
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, help_text='Leave blank to auto-populate from the uploaded file name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.ForeignKey(blank=True, help_text='Type of the uploaded file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tracker.filetype'),
        ),
        migrations.CreateModel(
            name='FileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='Extension without leading dot, e.g. pdf. Always stored lowercase.', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary extension for this file type.')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_extensions', to='tracker.filetype')),
            ],
            options={
                'verbose_name': 'File Extension',
                'verbose_name_plural': 'File Extensions',
                'ordering': ['-is_primary', 'extension'],
                'constraints': [models.UniqueConstraint(fields=('extension',), name='unique_file_extension'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('file_type',), name='unique_primary_extension_per_file_type')],
            },
        ),
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(help_text='MIME type string, e.g. application/pdf', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary MIME type for this file type.')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mime_types', to='tracker.filetype')),
            ],
            options={
                'verbose_name': 'MIME Type',
                'verbose_name_plural': 'MIME Types',
                'ordering': ['-is_primary', 'mime_type'],
                'constraints': [models.UniqueConstraint(fields=('mime_type',), name='unique_mime_type'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('file_type',), name='unique_primary_mime_type_per_file_type')],
            },
        ),
    ]
