# Generated by Django 6.0.3 on 2026-04-14 04:08

import taxtracker.tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_filetype_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBStoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Stored File',
                'verbose_name_plural': 'Stored Files',
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=taxtracker.tracker.models.DatabaseStorage(), upload_to=''),
        ),
    ]
