# Generated by Django 6.0.3 on 2026-05-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dbstoredfile_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='date',
            field=models.DateField(blank=True, help_text='Optional date for this attachment. Leave blank to auto-extract from the filename, or if no date can be found in the filename.', null=True),
        ),
    ]
