# Generated by Django 6.0.6 on 2026-06-23 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_initial_status_history(apps, schema_editor):
    FinancialYear = apps.get_model("tracker", "FinancialYear")
    FinancialYearStatusHistory = apps.get_model("tracker", "FinancialYearStatusHistory")
    for fy in FinancialYear.objects.all():
        FinancialYearStatusHistory.objects.create(
            financial_year=fy,
            from_status=None,
            to_status=fy.status,
        )


def delete_initial_status_history(apps, schema_editor):
    FinancialYearStatusHistory = apps.get_model("tracker", "FinancialYearStatusHistory")
    FinancialYearStatusHistory.objects.filter(from_status__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_attachment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='status',
            field=models.CharField(choices=[('pending_submission', 'Pending submission to tax agent'), ('submitted', 'Submitted to tax agent'), ('more_info_requested', 'Tax agent requests more info'), ('finalised', 'Finalised')], default='pending_submission', max_length=30),
        ),
        migrations.CreateModel(
            name='FinancialYearStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending_submission', 'Pending submission to tax agent'), ('submitted', 'Submitted to tax agent'), ('more_info_requested', 'Tax agent requests more info'), ('finalised', 'Finalised')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('pending_submission', 'Pending submission to tax agent'), ('submitted', 'Submitted to tax agent'), ('more_info_requested', 'Tax agent requests more info'), ('finalised', 'Finalised')], max_length=30)),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracker.financialyear')),
            ],
            options={
                'verbose_name': 'Financial Year Status Transition',
                'verbose_name_plural': 'Financial Year Status Transitions',
                'ordering': ['-transitioned_at', '-pk'],
            },
        ),
        migrations.RunPython(
            create_initial_status_history,
            delete_initial_status_history,
        ),
    ]
